### ISSUE TITLE
HELP!! Parametric t-SNE ERROR: MEMORY ERROR

### ISSUE THREAD

**Issue by kroscek** [kylemcdonald/Parametric-t-SNE#3]
Hi.
I tried the example of using t-sne as a loss function feed into keras layer.
But then i got an error when executing compute_joint_probabilities function: 

Precomputing P-values...
Traceback (most recent call last):

  File "<ipython-input-26-295bc03c11c2>", line 1, in <module>
    P = compute_joint_probabilities(all_data, batch_size=batch_size, verbose=2)

  File "<ipython-input-24-3493beb00de3>", line 83, in compute_joint_probabilities
    P = np.zeros((batch_count, batch_size, batch_size))
MemoryError

I'm not sure why? 
Note: I'm using Windows7, CONDA Python 2.7, CUDA installed with Theano backend

**Comment by kroscek** [comment]
Somehow it solves
